'use strict';
const kioskMode=document.body.dataset.mode==='kiosk';
const KEY='zielony-koszyk-v1';
const categories=['Warzywa i owoce','Pieczywo','Nabiał','Mięso i ryby','Napoje','Produkty sypkie','Słodycze'];
const seed=[['Pomidor malinowy','Warzywa i owoce',899,24,'kg','🍅'],['Banany','Warzywa i owoce',649,18,'kg','🍌'],['Jabłka polskie','Warzywa i owoce',399,32,'kg','🍎'],['Awokado','Warzywa i owoce',599,8,'szt.','🥑'],['Chleb wiejski','Pieczywo',699,12,'szt.','🍞'],['Croissant maślany','Pieczywo',349,7,'szt.','🥐'],['Mleko 3,2% · 1 l','Nabiał',389,40,'szt.','🥛'],['Ser gouda · 150 g','Nabiał',599,16,'szt.','🧀'],['Jajka · 10 szt.','Nabiał',1099,5,'szt.','🥚'],['Jogurt naturalny · 180 g','Nabiał',249,22,'szt.','🥛'],['Filet z kurczaka','Mięso i ryby',2399,9,'kg','🍗'],['Łosoś · 200 g','Mięso i ryby',1999,4,'szt.','🐟'],['Woda mineralna · 1,5 l','Napoje',219,56,'szt.','💧'],['Sok pomarańczowy · 1 l','Napoje',649,19,'szt.','🍊'],['Ryż biały · 1 kg','Produkty sypkie',549,25,'szt.','🍚'],['Makaron penne · 500 g','Produkty sypkie',429,6,'szt.','🍝'],['Czekolada mleczna · 100 g','Słodycze',499,20,'szt.','🍫'],['Ciastka owsiane · 200 g','Słodycze',749,13,'szt.','🍪']];
function fresh(){return {version:1,products:seed.map((p,i)=>({id:'p'+(i+1),name:p[0],category:p[1],price:p[2],stock:p[3],unit:p[4],emoji:p[5],barcode:String(5901234000000+i),vat:5})),sales:[]};}
const money=n=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN'}).format(n/100);
const qty=n=>new Intl.NumberFormat('pl-PL',{maximumFractionDigits:3}).format(n);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function validate(d){
 if(!d||d.version!==1||!Array.isArray(d.products)||!Array.isArray(d.sales)||d.products.length>10000||d.sales.length>50000)throw Error('Nieprawidłowy format bazy danych.');
 const ids=new Set(),codes=new Set();
 for(const p of d.products){if(!p||typeof p.id!=='string'||!p.id||ids.has(p.id)||typeof p.name!=='string'||!p.name.trim()||p.name.length>100||!categories.includes(p.category)||!Number.isSafeInteger(p.price)||p.price<=0||p.price>10000000||!Number.isFinite(p.stock)||p.stock<0||p.stock>100000||!['kg','szt.'].includes(p.unit)||(p.unit==='szt.'&&!Number.isInteger(p.stock))||typeof p.barcode!=='string'||!/^\d{8,14}$/.test(p.barcode)||codes.has(p.barcode)||typeof p.emoji!=='string'||p.emoji.length>16||![0,5,8,23].includes(p.vat))throw Error('Baza zawiera nieprawidłowy produkt lub powtórzony kod.');ids.add(p.id);codes.add(p.barcode);}
 const saleIds=new Set();
 for(const s of d.sales){if(!s||typeof s.id!=='string'||saleIds.has(s.id)||typeof s.number!=='string'||!Number.isFinite(Date.parse(s.date))||!['shop','cashier','self'].includes(s.mode)||!['Karta','Gotówka'].includes(s.payment)||!Array.isArray(s.items)||!s.items.length||!Number.isSafeInteger(s.total)||s.total<=0)throw Error('Nieprawidłowa historia sprzedaży.');saleIds.add(s.id);let total=0;for(const l of s.items){if(!l||typeof l.name!=='string'||!['kg','szt.'].includes(l.unit)||!Number.isSafeInteger(l.price)||l.price<=0||!Number.isFinite(l.quantity)||l.quantity<=0||l.quantity>100000||(l.unit==='szt.'&&!Number.isInteger(l.quantity))||![0,5,8,23].includes(l.vat)||l.sum!==Math.round(l.price*l.quantity))throw Error('Nieprawidłowa pozycja paragonu.');total+=l.sum;}if(total!==s.total||!Number.isSafeInteger(s.paid)||s.paid<s.total)throw Error('Nieprawidłowa suma paragonu.');}return d;
}
let db,storageError='';try{const raw=localStorage.getItem(KEY);db=raw?validate(JSON.parse(raw)):fresh();if(!raw)localStorage.setItem(KEY,JSON.stringify(db));}catch(e){db=fresh();storageError='Nie udało się odczytać bazy. Zapis jest zablokowany, aby chronić istniejące dane. Użyj importu poprawnej kopii lub innej przeglądarki.';}
function save(next,restore=false){if(storageError&&!restore)throw Error(storageError);validate(next);localStorage.setItem(KEY,JSON.stringify(next));db=next;if(restore)storageError='';}
const app=document.querySelector('#app'),modal=document.querySelector('#modal');
let route='dashboard',filter='',category='Wszystkie';const carts={shop:[],cashier:[],self:[]};
const titles={dashboard:'Pulpit sklepu',shop:'Sklep dla klienta',cashier:'Kasa tradycyjna',self:'Kasa samoobsługowa',inventory:'Produkty i magazyn',sales:'Historia sprzedaży',data:'Baza danych'};
const modeNames={shop:'Sklep online',cashier:'Kasa tradycyjna',self:'Samoobsługa'};
const date=s=>new Date(s).toLocaleString('pl-PL',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});
document.querySelector('#today').textContent=new Date().toLocaleDateString('pl-PL',{day:'numeric',month:'long',year:'numeric'});
function toast(s){const t=document.querySelector('#toast');t.textContent=s;t.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('visible'),3600);}
function show(html){document.querySelector('#modal-body').innerHTML=html;if(!modal.open)modal.showModal();}
function heading(title,sub,action=''){return `<div class="page-top"><div><h1>${title}</h1><p class="subtitle">${sub}</p></div>${action}</div>`;}
function todaySales(){return db.sales.filter(s=>new Date(s.date).toDateString()===new Date().toDateString());}
function salesTable(sales){return sales.length?`<div class="table-wrap"><table><thead><tr><th>NUMER TRANSAKCJI</th><th>DATA I GODZINA</th><th>KANAŁ SPRZEDAŻY</th><th>KWOTA</th><th>STATUS</th><th></th></tr></thead><tbody>${sales.map(s=>`<tr><td><strong>${esc(s.number)}</strong></td><td>${date(s.date)}</td><td>${modeNames[s.mode]}</td><td><strong>${money(s.total)}</strong></td><td><span class="badge">Opłacona · demo</span></td><td><button class="btn" data-receipt="${esc(s.id)}">Paragon</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Brak transakcji. Zrealizuj pierwszy zakup w sklepie lub przy kasie.</div>';}
function dashboard(){const sales=todaySales(),low=db.products.filter(p=>p.stock<8).sort((a,b)=>a.stock-b.stock),sum=sales.reduce((a,s)=>a+s.total,0);return heading('Dzień dobry, dobrze Cię widzieć 👋','Oto co dzieje się dziś w Twoim sklepie.', '<a class="btn" href="#inventory">＋ Dodaj / edytuj produkty</a>')+`<section class="hero"><div><div class="eyebrow">ŚWIEŻE PODEJŚCIE DO ZAKUPÓW</div><h2>Mały sklep.<br>Wielkie możliwości.</h2><p>Od pełnego koszyka do sprawnie działającej kasy.</p><a href="#shop" class="btn lime">Otwórz sklep &nbsp; ↗</a></div><div class="hero-art" aria-hidden="true">🥬</div></section><section class="stats">${[['Dzisiejsza sprzedaż',money(sum),'Wszystkie kanały sprzedaży','↗'],['Transakcje dzisiaj',sales.length,'Zakończone zakupy','▣'],['Produkty w bazie',db.products.length,'Twój aktualny asortyment','▤'],['Niski stan magazynowy',low.length,'Produkty poniżej 8 szt. / kg','◷']].map(s=>`<div class="stat"><div class="stat-top">${s[0]}<span class="stat-icon">${s[3]}</span></div><strong>${s[1]}</strong><small>${s[2]}</small></div>`).join('')}</section><div class="grid-two"><section class="panel"><div class="panel-title"><h2>Wszystko pod ręką</h2><span class="muted">↗</span></div><div class="quick-grid">${[['shop','♧','Zrób zakupy','Przeglądaj produkty i wypełnij koszyk.'],['cashier','▣','Obsłuż klienta','Skanuj produkty i rozlicz zakupy.'],['self','▦','Zeskanuj i zapłać','Wypróbuj kasę samoobsługową.']].map(x=>`<a class="quick" href="#${x[0]}"><span class="quick-icon">${x[1]}</span><strong>${x[2]}</strong><p>${x[3]}</p><span class="arrow">→</span></a>`).join('')}</div></section><section class="panel"><div class="panel-title"><h2>Warto uzupełnić</h2><a class="text-link" href="#inventory">Magazyn →</a></div>${low.slice(0,3).map(p=>`<div class="stock-row"><span class="mini-emoji">${esc(p.emoji)}</span><div><strong>${esc(p.name)}</strong><small>${esc(p.category)}</small></div><span class="badge warn">${qty(p.stock)} ${p.unit}</span></div>`).join('')||'<p class="muted">Wszystkie produkty są dostępne w odpowiedniej ilości.</p>'}</section></div><section class="panel"><div class="panel-title"><h2>Ostatnie transakcje</h2><a href="#sales" class="text-link">Zobacz wszystkie →</a></div>${salesTable(db.sales.slice().reverse().slice(0,5))}</section>`;}
function cart(){return carts[route]||[];}
function cartTotal(){return cart().reduce((s,l)=>{const p=db.products.find(p=>p.id===l.id);return s+(p?Math.round(p.price*l.quantity):0);},0);}
function basket(){return `<section class="panel basket"><div class="panel-title"><h2>Twój koszyk <span class="muted">(${cart().length})</span></h2><button class="btn" data-action="clear" ${!cart().length?'disabled':''}>Wyczyść</button></div>${cart().length?cart().map(l=>{const p=db.products.find(p=>p.id===l.id);return p?`<div class="cart-line"><div class="cart-line-top"><span>${esc(p.emoji)} ${esc(p.name)}</span><strong>${money(Math.round(p.price*l.quantity))}</strong></div><div class="quantity"><button data-change="${esc(p.id)}" data-delta="-1" aria-label="Zmniejsz ilość ${esc(p.name)}">−</button><span>${qty(l.quantity)} ${p.unit}</span><button data-change="${esc(p.id)}" data-delta="1" aria-label="Zwiększ ilość ${esc(p.name)}">+</button><button class="remove" data-remove="${esc(p.id)}">Usuń</button></div></div>`:'';}).join(''):'<div class="empty">🛒<p>Tu zaczynają się dobre zakupy.<br>Dodaj pierwszy produkt.</p></div>'}<div class="total"><span>Do zapłaty</span><span>${money(cartTotal())}</span></div><button class="btn primary full" data-action="checkout" ${!cart().length?'disabled':''}>${route==='shop'?'Zamów i zapłać':'Przejdź do płatności'} →</button><p class="note">Ceny brutto, zawierają VAT. Płatność symulowana — bez pobierania pieniędzy.</p></section>`;}
function matches(p){const q=filter.toLocaleLowerCase('pl');return (category==='Wszystkie'||p.category===category)&&(p.name.toLocaleLowerCase('pl').includes(q)||p.barcode.includes(q));}
function productCards(){const products=db.products.filter(matches);return products.map(p=>`<article class="product"><div class="product-visual" style="--tile:${['#eef2df','#faf0e1','#edf2f5','#f8eae4','#e8f2e8','#f4efdf','#f7e9eb'][categories.indexOf(p.category)]}">${esc(p.emoji)}${p.stock<8?`<span class="badge warn">${p.stock===0?'Wyprzedane':'Ostatnie sztuki'}</span>`:''}</div><h3>${esc(p.name)}</h3><small>${qty(p.stock)} ${p.unit} w magazynie</small><div class="product-bottom"><strong>${money(p.price)}<small> / ${p.unit}</small></strong><button class="btn primary add" data-add="${esc(p.id)}" aria-label="Dodaj ${esc(p.name)}" ${p.stock<=0?'disabled':''}>+</button></div></article>`).join('')||'<div class="empty">Nie znaleziono produktów.</div>';}
function shopping(){return heading(titles[route],route==='shop'?'Świeże produkty, codziennie blisko Ciebie.':'Tryb demonstracyjny · wszystkie transakcje trafiają do wspólnego magazynu.',`<span class="badge">● ${route==='shop'?'Sklep otwarty':'Kasa gotowa'}</span>`)+`${route==='self'?'<div class="self-banner"><span>👋</span><div><h2>Twoje zakupy, Twoje tempo.</h2><p>1. Zeskanuj lub wybierz produkty &nbsp; → &nbsp; 2. Sprawdź koszyk &nbsp; → &nbsp; 3. Zapłać kartą</p></div></div>':''}<div class="shopping-layout"><div>${route!=='shop'?'<div class="scanner"><label for="barcode">Skaner kodów kreskowych</label><form id="scan-form"><input id="barcode" name="barcode" inputmode="numeric" placeholder="Wpisz kod produktu…" autocomplete="off" required><button class="btn primary">Skanuj ↵</button></form><button type="button" class="btn" data-manual-code style="margin-top:10px">Wpisz kod ręcznie</button><p>Wypróbuj: 5901234000004 — chleb wiejski. Możesz też wybrać produkt poniżej.</p></div>':''}<div class="toolbar"><input class="search" id="search" aria-label="Szukaj produktów" placeholder="⌕  Szukaj produktu lub kodu…" value="${esc(filter)}"></div><div class="chips">${['Wszystkie',...categories].map(c=>`<button class="chip ${category===c?'active':''}" data-category="${c}">${c}</button>`).join('')}</div><div class="products" id="product-list">${productCards()}</div></div><div id="basket-area">${basket()}</div></div>`;}
function inventoryRows(){return db.products.filter(matches).map(p=>`<tr><td><span class="mini-emoji">${esc(p.emoji)}</span></td><td><strong>${esc(p.name)}</strong><br><small class="muted">${esc(p.barcode)}</small></td><td>${p.category}</td><td>${money(p.price)} / ${p.unit}</td><td><span class="badge ${p.stock<8?'warn':''}">${qty(p.stock)} ${p.unit}</span></td><td>${p.vat}%</td><td><button class="btn" data-edit="${esc(p.id)}">Edytuj</button> <button class="btn danger" data-delete="${esc(p.id)}">Usuń</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">Brak produktów.</td></tr>';}
function inventory(){return heading('Produkty i magazyn','Zarządzaj asortymentem, cenami i dostępnością produktów.','<button class="btn primary" data-action="new">＋ Dodaj produkt</button>')+`<div class="panel"><div class="toolbar"><input class="search" id="search" placeholder="Szukaj nazwy lub kodu…" aria-label="Szukaj produktów" value="${esc(filter)}"><select id="category-select" aria-label="Kategoria">${['Wszystkie',...categories].map(c=>`<option ${c===category?'selected':''}>${c}</option>`).join('')}</select></div><div class="table-wrap"><table><thead><tr><th></th><th>PRODUKT / KOD</th><th>KATEGORIA</th><th>CENA BRUTTO</th><th>STAN</th><th>VAT</th><th>OPERACJE</th></tr></thead><tbody id="inventory-rows">${inventoryRows()}</tbody></table></div></div>`;}
function salesPage(){const revenue=db.sales.reduce((a,s)=>a+s.total,0);return heading('Historia sprzedaży','Każdy zakup w jednym miejscu. Wybierz transakcję, aby zobaczyć paragon.','<button class="btn" data-action="csv">↓ Eksport CSV</button>')+`<div class="stats">${[['Łączny przychód',money(revenue)],['Liczba transakcji',db.sales.length],['Średni koszyk',money(db.sales.length?Math.round(revenue/db.sales.length):0)],['Sprzedaż dzisiaj',money(todaySales().reduce((a,s)=>a+s.total,0))]].map(s=>`<div class="stat"><div class="stat-top">${s[0]}</div><strong>${s[1]}</strong></div>`).join('')}</div><div class="panel">${salesTable(db.sales.slice().reverse())}</div>`;}
function dataPage(){return heading('Baza danych','Lokalna baza Twojego sklepu. Zapisuj kopie i przenoś dane między urządzeniami.')+`<div class="data-status">${storageError?esc(storageError):'● Baza aktywna · automatyczny zapis w tej przeglądarce'}<br><strong>${db.products.length}</strong> produktów &nbsp; · &nbsp; <strong>${db.sales.length}</strong> transakcji &nbsp; · &nbsp; Format JSON, wersja 1</div><div class="data-grid"><section class="panel"><div class="data-icon">↧</div><h2>Kopia zapasowa</h2><p>Pobierz produkty, stany magazynowe i pełną historię sprzedaży jako plik JSON.</p><button class="btn primary" data-action="export">Pobierz bazę JSON</button></section><section class="panel"><div class="data-icon">↥</div><h2>Przywróć bazę</h2><p>Wczytaj wcześniej wyeksportowany plik. Import zastąpi aktualną bazę po potwierdzeniu.</p><label class="btn file-label">Wybierz plik JSON<input type="file" id="import-file" accept=".json,application/json"></label></section><section class="panel"><h2>Jak przechowywane są dane?</h2><p>Aplikacja korzysta z localStorage. Dane pozostają po odświeżeniu strony, ale dotyczą tej przeglądarki i adresu strony. Wyczyszczenie danych przeglądarki usuwa bazę. Wykonuj kopie zapasowe.</p><p>GitHub Pages udostępnia statyczne pliki. Współdzielenie bazy między urządzeniami i prawdziwe konta wymagają dodatkowego backendu. Panele w tym projekcie są trybami demonstracyjnymi, bez logowania.</p></section><section class="panel"><h2>Zacznij od nowa</h2><p>Przywróć 18 przykładowych produktów i usuń historię demonstracyjną. Przed resetem pobierz kopię bazy.</p><button class="btn danger" data-action="reset">Przywróć dane przykładowe</button></section></div>`;}
function render(){document.querySelector('#page-name').textContent=titles[route];document.querySelectorAll('nav a').forEach(a=>{a.classList.toggle('active',a.hash==='#'+route);if(a.hash==='#'+route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});app.innerHTML=kioskMode?kioskScreen():({dashboard,shop:shopping,cashier:shopping,self:selfPanel,inventory,sales:salesPage,data:dataPage}[route])();if(!kioskMode&&route==='self')mountSelfPanel();}
function navigate(){route=kioskMode?'self':location.hash.slice(1);if(!titles[route])route='dashboard';filter='';category='Wszystkie';modal.close();render();focusScanner();}
function focusScanner(){if(!modal.open&&(route==='self'||route==='cashier')){const input=document.querySelector('#barcode');if(kioskMode&&input)input.inputMode='none';input?.focus({preventScroll:true});}}
function scanCode(code){try{const p=db.products.find(p=>p.barcode===String(code).trim());if(!p)throw Error('Nieznany kod: '+code+'. Poproś obsługę o dodanie produktu.');addProduct(p.id);}finally{const input=document.querySelector('#barcode');if(input)input.value='';focusScanner();}}
modal.addEventListener('close',focusScanner);
window.addEventListener('hashchange',navigate);
function refreshBasket(){if(kioskMode){render();focusScanner();}else document.querySelector('#basket-area').innerHTML=basket();}
function addProduct(productId,amount){const p=db.products.find(p=>p.id===productId);if(!p)return;if(amount===undefined&&p.unit==='kg'){show(`<div class="modal-heading"><h2>Zważ produkt</h2><button class="close" data-action="close" aria-label="Zamknij">×</button></div><p>${esc(p.emoji)} ${esc(p.name)} · ${money(p.price)} / kg</p><form id="weight-form" data-id="${esc(p.id)}"><label class="field">Masa w kilogramach<input name="weight" type="number" min="0.001" max="${p.stock}" step="0.001" value="0.5" required autofocus></label><p class="note">Symulator wagi — wpisz odczytaną masę, np. 0,5 kg.</p><p class="error" id="form-error"></p><div class="actions"><button class="btn primary">Dodaj do koszyka</button></div></form>`);return;}amount=amount??1;const l=cart().find(l=>l.id===p.id);const next=Math.round(((l?.quantity||0)+amount)*1000)/1000;if(next>p.stock)throw Error('Brak wystarczającej ilości w magazynie.');if(l)l.quantity=next;else cart().push({id:p.id,quantity:amount});if(kioskMode)lastScanned={id:p.id,quantity:amount};refreshBasket();toast('Dodano: '+p.name);}
function productForm(productId){const p=db.products.find(p=>p.id===productId)||{id:'',name:'',barcode:'',category:categories[0],price:100,stock:0,unit:'szt.',emoji:'🛒',vat:5};show(`<div class="modal-heading"><h2>${p.id?'Edytuj produkt':'Nowy produkt'}</h2><button class="close" data-action="close" aria-label="Zamknij">×</button></div><form id="product-form" data-id="${esc(p.id)}"><div class="form-grid"><label class="field wide">Nazwa produktu<input name="name" value="${esc(p.name)}" maxlength="100" required></label><label class="field wide">Kod kreskowy (8–14 cyfr)<input name="barcode" value="${esc(p.barcode)}" pattern="[0-9]{8,14}" required inputmode="numeric"></label><label class="field">Kategoria<select name="category">${categories.map(c=>`<option ${c===p.category?'selected':''}>${c}</option>`).join('')}</select></label><label class="field">Ikona / emoji<input name="emoji" value="${esc(p.emoji)}" maxlength="16" required></label><label class="field">Cena brutto (zł)<input type="number" name="price" min="0.01" max="100000" step="0.01" value="${(p.price/100).toFixed(2)}" required></label><label class="field">Stan magazynowy<input type="number" name="stock" min="0" max="100000" step="0.001" value="${p.stock}" required></label><label class="field">Jednostka<select name="unit"><option ${p.unit==='szt.'?'selected':''}>szt.</option><option ${p.unit==='kg'?'selected':''}>kg</option></select></label><label class="field">VAT (demonstracyjny)<select name="vat">${[0,5,8,23].map(v=>`<option value="${v}" ${v===p.vat?'selected':''}>${v}%</option>`).join('')}</select></label></div><p class="error" id="form-error"></p><div class="actions"><button type="button" class="btn" data-action="close">Anuluj</button><button class="btn primary">Zapisz produkt</button></div></form>`);}
function checkout(){if(!cart().length)return;show(`<div class="modal-heading"><h2>Finalizacja zakupów</h2><button class="close" data-action="close" aria-label="Zamknij">×</button></div><div class="total"><span>Do zapłaty</span><span>${money(cartTotal())}</span></div><form id="payment-form"><label class="field">Metoda płatności<select id="payment-method" name="method"><option>Karta</option>${route==='cashier'?'<option>Gotówka</option>':''}</select></label><label class="field" id="cash-field" hidden style="margin-top:15px">Otrzymana gotówka (zł)<input name="paid" type="number" min="0" step="0.01"></label><p class="note">To symulacja. Nie podawaj danych karty. Zatwierdzenie zapisze sprzedaż i zaktualizuje magazyn.</p><p class="error" id="form-error"></p><div class="actions"><button type="button" class="btn" data-action="close">Wróć</button><button class="btn primary">Potwierdź płatność</button></div></form>`);document.querySelector('#cash-field').style.display='none';}
function purchase(method,paid){const current=validate(JSON.parse(localStorage.getItem(KEY)));const items=cart().map(l=>{const p=current.products.find(p=>p.id===l.id),old=db.products.find(p=>p.id===l.id);if(!p||p.stock<l.quantity)throw Error('Stan magazynu zmienił się. Sprawdź koszyk.');if(p.price!==old?.price||p.unit!==old?.unit||p.vat!==old?.vat)throw Error('Dane produktu zmieniły się. Odśwież stronę i sprawdź koszyk.');return {id:p.id,name:p.name,price:p.price,quantity:l.quantity,unit:p.unit,vat:p.vat,sum:Math.round(p.price*l.quantity)};});if(!items.length)throw Error('Koszyk jest pusty.');const total=items.reduce((a,l)=>a+l.sum,0);if(total<=0)throw Error('Wartość zakupu musi wynosić przynajmniej 0,01 zł.');if(method==='Gotówka'&&(!Number.isSafeInteger(paid)||paid<total))throw Error('Otrzymana kwota jest mniejsza niż wartość zakupów.');const s={id:id(),number:'ZK-'+new Date().getFullYear()+'-'+String(current.sales.length+1).padStart(5,'0'),date:new Date().toISOString(),mode:route,payment:method,paid:method==='Gotówka'?paid:total,items,total};items.forEach(l=>{const p=current.products.find(p=>p.id===l.id);p.stock=Math.round((p.stock-l.quantity)*1000)/1000;});current.sales.push(s);save(current);carts[route]=[];render();receipt(s.id);}
function receipt(saleId){const s=db.sales.find(s=>s.id===saleId);if(!s)return;const tax=s.items.reduce((a,l)=>a+l.sum-Math.round(l.sum/(1+l.vat/100)),0);show(`<div class="modal-heading"><h2>Zakup zakończony ✓</h2><button class="close" data-action="close" aria-label="Zamknij">×</button></div><div class="receipt"><div class="receipt-head"><strong>ZIELONY KOSZYK</strong><br>PARAGON DEMONSTRACYJNY — NIEFISKALNY<br>${esc(s.number)}<br>${date(s.date)} · ${modeNames[s.mode]}</div>${s.items.map(l=>`<div>${esc(l.name)}</div><div class="receipt-line"><span>${qty(l.quantity)} ${l.unit} × ${money(l.price)} · VAT ${l.vat}%</span><strong>${money(l.sum)}</strong></div>`).join('')}<div class="receipt-line receipt-total"><span>SUMA</span><span>${money(s.total)}</span></div><div class="receipt-line"><span>W tym VAT</span><span>${money(tax)}</span></div><div class="receipt-line"><span>Płatność</span><span>${s.payment}</span></div>${s.payment==='Gotówka'?`<div class="receipt-line"><span>Otrzymano</span><span>${money(s.paid)}</span></div><div class="receipt-line"><span>Reszta</span><strong>${money(s.paid-s.total)}</strong></div>`:''}<p style="text-align:center">Dziękujemy za zakupy!<br>Dokument edukacyjny. Brak rzeczywistej płatności.</p></div><div class="actions"><button class="btn" data-action="print">Drukuj paragon</button><button class="btn primary" data-action="close">Gotowe</button></div>`);}
function download(name,content,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function confirmDialog(title,description,action){show(`<div class="modal-heading"><h2>${title}</h2><button class="close" data-action="close" aria-label="Zamknij">×</button></div><p>${description}</p><div class="actions"><button class="btn" data-action="close">Anuluj</button><button class="btn primary" id="confirm-button">Potwierdź</button></div>`);document.querySelector('#confirm-button').onclick=()=>{try{action();modal.close();render();}catch(e){toast(e.message);}};}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.add)addProduct(b.dataset.add);if(b.dataset.category){category=b.dataset.category;render();}if(b.dataset.change){const l=cart().find(l=>l.id===b.dataset.change),p=db.products.find(p=>p.id===l.id),n=Math.round((l.quantity+Number(b.dataset.delta)*(p.unit==='kg'?0.1:1))*1000)/1000;if(n>p.stock)throw Error('Brak większej ilości w magazynie.');if(n<=0)carts[route]=cart().filter(x=>x!==l);else l.quantity=n;refreshBasket();}if(b.dataset.remove){carts[route]=cart().filter(l=>l.id!==b.dataset.remove);refreshBasket();}if(b.dataset.edit)productForm(b.dataset.edit);if(b.dataset.delete)confirmDialog('Usuń produkt','Produkt zostanie usunięty z katalogu. Wcześniejsze paragony pozostaną w historii.',()=>{const next=structuredClone(db);next.products=next.products.filter(p=>p.id!==b.dataset.delete);save(next);Object.keys(carts).forEach(k=>carts[k]=carts[k].filter(l=>l.id!==b.dataset.delete));toast('Produkt usunięty.');});if(b.dataset.receipt)receipt(b.dataset.receipt);switch(b.dataset.action){case 'new':productForm();break;case 'close':modal.close();break;case 'clear':carts[route]=[];refreshBasket();break;case 'checkout':checkout();break;case 'print':window.print();break;case 'export':download('zielony-koszyk-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(db,null,2),'application/json');break;case 'csv':download('sprzedaz.csv','\uFEFFNumer;Data;Kanał;Płatność;Kwota PLN\r\n'+db.sales.map(s=>[s.number,date(s.date),modeNames[s.mode],s.payment,(s.total/100).toFixed(2).replace('.',',')].map(v=>'"'+String(v).replace(/^[=+@-]/,"'").replace(/"/g,'""')+'"').join(';')).join('\r\n'),'text/csv;charset=utf-8');break;case 'reset':confirmDialog('Przywrócić dane przykładowe?','Usuniesz obecną historię i produkty. Operacji nie można cofnąć bez kopii JSON.',()=>{save(fresh(),true);Object.keys(carts).forEach(k=>carts[k]=[]);toast('Przywrócono dane przykładowe.');});break;}}catch(e){toast(e.message);}});
document.addEventListener('input',e=>{if(e.target.id==='search'){filter=e.target.value;if(route==='inventory')document.querySelector('#inventory-rows').innerHTML=inventoryRows();else document.querySelector('#product-list').innerHTML=productCards();}});
document.addEventListener('change',async e=>{if(e.target.id==='category-select'){category=e.target.value;document.querySelector('#inventory-rows').innerHTML=inventoryRows();}if(e.target.id==='payment-method'){const field=document.querySelector('#cash-field');field.hidden=e.target.value!=='Gotówka';field.style.display=field.hidden?'none':'flex';field.querySelector('input').required=!field.hidden;}if(e.target.id==='import-file'){const f=e.target.files[0];if(!f)return;try{if(f.size>10*1024*1024)throw Error('Maksymalny rozmiar kopii to 10 MB.');const imported=validate(JSON.parse(await f.text()));confirmDialog('Zaimportować bazę?',`Plik zawiera ${imported.products.length} produktów i ${imported.sales.length} transakcji. Zastąpi obecną bazę i wyczyści koszyki.`,()=>{save(imported,true);Object.keys(carts).forEach(k=>carts[k]=[]);toast('Baza została zaimportowana.');});}catch(err){toast('Import odrzucony: '+err.message);}e.target.value='';}});
document.addEventListener('submit',async e=>{e.preventDefault();const form=e.target,data=new FormData(form);try{if(form.id==='scan-form'){scanCode(data.get('barcode'));}if(form.id==='weight-form'){const amount=Number(data.get('weight'));if(!Number.isFinite(amount)||amount<=0||Math.abs(amount*1000-Math.round(amount*1000))>0.00001)throw Error('Podaj masę z dokładnością do 0,001 kg.');addProduct(form.dataset.id,amount);modal.close();}if(form.id==='product-form'){const product={id:form.dataset.id||id(),name:String(data.get('name')).trim(),barcode:String(data.get('barcode')).trim(),category:data.get('category'),emoji:String(data.get('emoji')).trim(),price:Math.round(Number(data.get('price'))*100),stock:Number(data.get('stock')),unit:data.get('unit'),vat:Number(data.get('vat'))};if(db.products.some(p=>p.id!==product.id&&p.barcode===product.barcode))throw Error('Ten kod kreskowy jest już używany.');if(product.unit==='szt.'&&!Number.isInteger(product.stock))throw Error('Dla sztuk podaj całkowity stan magazynowy.');const next=structuredClone(db),i=next.products.findIndex(p=>p.id===product.id);if(i<0)next.products.push(product);else next.products[i]=product;save(next);Object.keys(carts).forEach(k=>carts[k]=carts[k].filter(l=>l.id!==product.id));modal.close();render();toast('Produkt zapisany.');}if(form.id==='payment-form'){const method=data.get('method'),paid=Math.round(Number(data.get('paid'))*100);if(navigator.locks)await navigator.locks.request(KEY,()=>purchase(method,paid));else purchase(method,paid);}}catch(err){const error=document.querySelector('#form-error');if(modal.open&&error)error.textContent=err.message;else toast(err.message);}});
window.addEventListener('storage',e=>{if(e.key===KEY){try{db=validate(JSON.parse(e.newValue));Object.keys(carts).forEach(k=>carts[k]=carts[k].filter(l=>db.products.some(p=>p.id===l.id)));modal.close();render();toast('Baza zaktualizowana w innej karcie.');}catch{storageError='Dane zmieniły się w innej karcie. Odśwież stronę lub zaimportuj kopię bazy.';toast(storageError);}}});
navigate();if(storageError)toast(storageError);
