'use strict';
let lastScanned=null;
function selfPanel(){return heading('Kasa samoobsługowa','Otwórz stanowisko kasowe lub przejdź do zarządzania sklepem.')+`<div class="station-launch"><section class="station-card"><span class="station-kicker">STANOWISKO KLIENTA</span><h2>Kasa samoobsługowa</h2><p>Zeskanuj kod QR na tablecie lub otwórz emulator na tym urządzeniu.</p><div class="qr-frame"><div id="station-qr" aria-label="Kod QR do emulatora"></div></div><p id="qr-status" class="note" role="status"></p><a class="btn primary station-open" href="kasa.html" target="_blank" rel="noopener">Otwórz emulator ↗</a><details class="qr-settings"><summary>Adres kasy dla kodu QR</summary><form id="qr-form"><label class="field">Adres opublikowanej kasy<input id="qr-url" type="url" placeholder="https://twoja-strona.github.io/sklep/kasa.html" required></label><button class="btn" type="submit">Generuj kod QR</button></form></details></section><section class="station-card station-admin"><span class="station-kicker">ZARZĄDZANIE SKLEPEM</span><div class="admin-illustration" aria-hidden="true"><span>▤</span><div><i></i><i></i><i></i></div></div><h2>Pulpit administracyjny</h2><p>Zarządzaj produktami, uzupełniaj magazyn i sprawdzaj historię sprzedaży.</p><a class="btn primary station-open" href="#dashboard">Przejdź do pulpitu administracyjnego →</a><p class="note">Panel administracyjny otwiera się tutaj. Ekran klienta pozostaje oddzielną stroną.</p></section></div>`;}
function mountSelfPanel(){
 const container=document.querySelector('#station-qr');if(!container)return;
 let url='';try{url=localStorage.getItem('zielony-koszyk-public-url')||'';}catch{}
 if(!url&&/^https?:$/.test(location.protocol))url=new URL('kasa.html',location.href).href;
 document.querySelector('#qr-url').value=url;
 if(url)drawStationQR(url);else{container.innerHTML='<span class="qr-placeholder" aria-hidden="true">▦</span>';document.querySelector('#qr-status').textContent='Otworzono plik lokalny. Wpisz poniżej adres kasy na GitHub Pages, aby wygenerować kod QR do skanowania na tablecie.';document.querySelector('.qr-settings').open=true;}
}
function drawStationQR(value){
 const container=document.querySelector('#station-qr'),status=document.querySelector('#qr-status');
 try{const url=new URL(value);if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw Error('Wpisz adres HTTP lub HTTPS bez danych logowania.');if(url.href.length>1500)throw Error('Adres jest zbyt długi.');
  container.replaceChildren();new QRCode(container,{text:url.href,width:224,height:224,colorDark:'#172f25',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});
  const local=['localhost','127.0.0.1','[::1]'].includes(url.hostname);
  status.textContent=local?'Ten adres działa tylko na bieżącym urządzeniu. Dla tabletu wpisz publiczny adres GitHub Pages.':'Zeskanuj aparatem tabletu, aby otworzyć kasę. QR zawiera adres strony, bez danych sklepu.';
  container.title=url.href;return url.href;
 }catch(error){status.textContent='Nie udało się wygenerować QR: '+error.message;return null;}
}
function kioskScreen(){
 const lines=cart().map(l=>({line:l,product:db.products.find(p=>p.id===l.id)})).filter(x=>x.product);
 if(!lines.length)lastScanned=null;
 const recent=lastScanned&&lines.find(x=>x.product.id===lastScanned.id),p=recent?.product;
 const total=cartTotal(),weight=p?.unit==='kg'?lastScanned.quantity:0;
 return `<div class="checkout-terminal"><section class="terminal-main"><div class="last-item" aria-live="polite">${p?`<div class="last-item-row"><h1>${esc(p.name)}</h1><strong>${money(Math.round(p.price*lastScanned.quantity))}</strong></div><p class="last-item-quantity">${qty(lastScanned.quantity)} ${p.unit} × ${money(p.price)}/${p.unit}</p><span class="scan-confirmation">✓ Produkt dodany</span>`:'<div class="scan-welcome"><svg viewBox="0 0 120 90" aria-hidden="true"><path d="M18 28V12h20M82 12h20v16M102 62v16H82M38 78H18V62" fill="none" stroke="currentColor" stroke-width="3"/><path d="M32 30v30m8-30v30m5-30v30m9-30v30m6-30v30m10-30v30m5-30v30m11-30v30" stroke="currentColor" stroke-width="3"/><path d="M8 45h104" stroke="#da4947" stroke-width="2"/></svg><h1>Witaj! Zeskanuj pierwszy produkt.</h1><p>Przyłóż kod kreskowy do czytnika.</p></div>'}</div><div class="scan-guidance"><span class="scanner-light"></span>${p?'Proszę zeskanować kolejny artykuł.':'Możesz też wyszukać artykuł lub wprowadzić kod.'}</div><div class="terminal-scanner"><form id="scan-form"><label for="barcode" class="sr-only">Kod kreskowy</label><input id="barcode" name="barcode" inputmode="none" autocomplete="off" placeholder="Czytnik gotowy · zeskanuj kod" required><button type="submit" aria-label="Dodaj zeskanowany kod">↵</button></form></div><button class="terminal-search" data-terminal="search"><span>▤</span> Wyszukaj po nazwie lub wprowadź kod <span>›</span></button><div class="terminal-controls"><button data-terminal="help"><span>♟</span>Pomoc</button><button data-terminal="cancel"><span>⊗</span>Anuluj zakupy</button><button data-terminal="info"><span>▧</span>Informacje</button><div class="terminal-weight"><strong>${weight.toLocaleString('pl-PL',{minimumFractionDigits:3,maximumFractionDigits:3})}<small> kg</small></strong><span>Masa ostatniego produktu · symulacja</span></div></div></section><aside class="terminal-receipt"><div class="terminal-receipt-title"><span>🛒 Twoje zakupy</span><span>${lines.length} poz.</span></div><div class="receipt-items">${lines.length?lines.map(({line:l,product:p})=>`<div class="terminal-line"><div><span>${esc(p.name)}</span><strong>${money(Math.round(p.price*l.quantity))}</strong></div><small>${qty(l.quantity)} ${p.unit} × ${money(p.price)}</small><button data-terminal-remove="${esc(p.id)}" aria-label="Usuń ${esc(p.name)}">×</button></div>`).join(''):'<p class="receipt-empty">Zeskanowane produkty<br>pojawią się w tym miejscu.</p>'}</div><div class="receipt-summary"><div><span>Wartość produktów</span><span>${money(total)}</span></div><div><span>Rabaty</span><span>${money(0)}</span></div><div class="summary-total"><span>Suma</span><strong>${money(total)}</strong></div></div><button class="terminal-pay" data-action="checkout" ${lines.length?'':'disabled'}><span>Zapłać</span><strong>${money(total)}</strong><span>›</span></button><span class="terminal-demo">Płatność demonstracyjna</span></aside></div>`;
}
function terminalSearch(){show(`<div class="modal-heading"><h2>Znajdź produkt</h2><button class="close" data-action="close" aria-label="Zamknij">×</button></div><label class="field">Nazwa lub kod kreskowy<input id="terminal-query" type="search" placeholder="Np. chleb, banany lub kod z opakowania" autocomplete="off"></label><div class="terminal-results" id="terminal-results">${terminalResults('')}</div>`);document.querySelector('#terminal-query').focus();}
function terminalResults(query){const q=query.trim().toLocaleLowerCase('pl');return db.products.filter(p=>p.name.toLocaleLowerCase('pl').includes(q)||p.barcode.includes(q)).map(p=>`<button class="terminal-result" data-terminal-product="${esc(p.id)}" ${p.stock<=0?'disabled':''}><span>${esc(p.emoji)}</span><span><strong>${esc(p.name)}</strong><small>${p.stock>0?money(p.price)+' / '+p.unit:'Niedostępny'}</small></span><b>＋</b></button>`).join('')||'<p class="empty">Nie znaleziono produktu. Poproś obsługę o pomoc.</p>';}
document.addEventListener('input',e=>{if(e.target.id==='terminal-query')document.querySelector('#terminal-results').innerHTML=terminalResults(e.target.value);});
document.addEventListener('submit',e=>{if(e.target.id==='qr-form'){e.preventDefault();const url=drawStationQR(document.querySelector('#qr-url').value);if(url){try{localStorage.setItem('zielony-koszyk-public-url',url);}catch{}toast('Kod QR gotowy.');}}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;try{
 if(b.dataset.terminalProduct){modal.close();addProduct(b.dataset.terminalProduct);focusScanner();}
 if(b.dataset.terminalRemove)confirmDialog('Usunąć produkt?','Wybrany produkt zostanie usunięty z bieżących zakupów.',()=>{carts.self=carts.self.filter(l=>l.id!==b.dataset.terminalRemove);if(lastScanned?.id===b.dataset.terminalRemove)lastScanned=null;});
 if(b.dataset.terminal==='search')terminalSearch();
 if(b.dataset.terminal==='cancel'&&cart().length)confirmDialog('Anulować zakupy?','Wszystkie pozycje zostaną usunięte z koszyka. Nie zapisano jeszcze sprzedaży.',()=>{carts.self=[];lastScanned=null;});
 if(b.dataset.terminal==='help')show('<div class="modal-heading"><h2>Pomoc przy kasie</h2><button class="close" data-action="close" aria-label="Zamknij">×</button></div><p>Poproś obsługę sklepu o podejście do stanowiska.</p><p>Produkt bez kodu znajdziesz przez przycisk wyszukiwania. Produkt na wagę wymaga podania masy.</p><p class="note">Emulator nie wysyła automatycznego powiadomienia do pracownika.</p><button class="btn primary full" data-action="close">Wróć do zakupów</button>');
 if(b.dataset.terminal==='info')show('<div class="modal-heading"><h2>Informacje o zakupach</h2><button class="close" data-action="close" aria-label="Zamknij">×</button></div><p>Wszystkie ceny są cenami brutto. Po zatwierdzeniu płatności otrzymasz paragon demonstracyjny.</p><p>Nie pobieramy prawdziwych pieniędzy. Stan magazynu i historia sprzedaży aktualizują się w tej przeglądarce.</p><button class="btn primary full" data-action="close">Rozumiem</button>');
 }catch(error){toast(error.message);}});
